### ISSUE TITLE
Broken on FF47 (NOT because of e10s)

### ISSUE THREAD

**Issue by mzso** [Infocatcher/Addons_Quick_Search#4]
Typing an addons name doesn't select the addon.
It still works on 45(beta ATM).
I tested it with e10s disabled too.

**Comment by mzso** [comment]
Nevermind...
Apparently it's a dupe of the issue you opened: #4
You just didn't make a relase with the fix. Making/installing an addon from master restores the functionality.

**Comment by Infocatcher** [comment]
> Making/installing an addon from master restores the functionality.

Great. Thanks for testing.
So, I close this in favor of #3.

**Comment by mzso** [comment]
Okay. So are you going to release a new version with the fix?

**Comment by Infocatcher** [comment]
https://addons.mozilla.org/addon/addons-quick-search/versions/0.1.2
I hope, will be reviewed soon...
